[package]
name = "crypto_box_sample"
version = "0.0.1"
authors = ["glassonion1 <glassonion999@gmail.com>"]
edition = "2018"

[dependencies]
crypto_box = "0.6.1"
rand_core = { version = "0.6", features = ["getrandom"] }